In [23]:
import numpy as np

# Matrix Pair 1
A1 = np.array([[3, 8, 2], [4, 1, 7], [6, 5, 9]])
B1 = np.array([[7, 0, 5], [2, 8, 1], [9, 6, 3]])

# Matrix Pair 2
A2 = np.array([[8, 1, 3], [0, 7, 4], [5, 2, 6]])
B2 = np.array([[4, 9, 2], [1, 3, 6], [7, 0, 8]])

# Matrix Pair 3
A3 = np.array([[9, -4, 7], [-1, 3, -2], [6, 0, 5]])
B3 = np.array([[-3, 1, 8], [7, -6, 0], [2, 9, -4]])

# Matrix Pair 4
A4 = np.array([[2, -6, 0], [8, -1, -7], [5, 9, 3]])
B4 = np.array([[1, 4, -9], [0, -7, 2], [-3, 5, 8]])

# Matrix Pair 5
A5 = np.array([[0, -3, 8], [9, 6, -1], [-7, 2, 4]])
B5 = np.array([[-5, 8, -7], [1, 0, -2], [6, -4, 3]])

# Perform matrix multiplications
result1_dot = np.dot(A1, B1)
result2_dot = np.dot(A2, B2)
result3_matmul = np.matmul(A3, B3)
result4_matmul = np.matmul(A4, B4)
result5_matmul = np.matmul(A5, B5)

print(f'A1 = \n{A1}\n')
print(f'B1 = \n{B1}\n')
print(f'A1 * B1 = \n{result1_dot}\n\n\n\n')

print(f'A2 = \n{A2}\n')
print(f'B2 = \n{B2}\n')
print(f'A2 * B2 = \n{result2_dot}\n\n\n\n')

print(f'A3 = \n{A3}\n')
print(f'B3 = \n{B3}\n')
print(f'A3 * B3 = \n{result3_matmul}\n\n\n\n')

print(f'A4 = \n{A4}\n')
print(f'B4 = \n{B4}\n')
print(f'A4 * B4 = \n{result4_matmul}\n\n\n\n')

print(f'A5 = \n{A5}\n')
print(f'B5 = \n{B5}\n')
print(f'A5 * B5 = \n{result5_matmul}')

A1 = 
[[3 8 2]
 [4 1 7]
 [6 5 9]]

B1 = 
[[7 0 5]
 [2 8 1]
 [9 6 3]]

A1 * B1 = 
[[ 55  76  29]
 [ 93  50  42]
 [133  94  62]]




A2 = 
[[8 1 3]
 [0 7 4]
 [5 2 6]]

B2 = 
[[4 9 2]
 [1 3 6]
 [7 0 8]]

A2 * B2 = 
[[54 75 46]
 [35 21 74]
 [64 51 70]]




A3 = 
[[ 9 -4  7]
 [-1  3 -2]
 [ 6  0  5]]

B3 = 
[[-3  1  8]
 [ 7 -6  0]
 [ 2  9 -4]]

A3 * B3 = 
[[-41  96  44]
 [ 20 -37   0]
 [ -8  51  28]]




A4 = 
[[ 2 -6  0]
 [ 8 -1 -7]
 [ 5  9  3]]

B4 = 
[[ 1  4 -9]
 [ 0 -7  2]
 [-3  5  8]]

A4 * B4 = 
[[   2   50  -30]
 [  29    4 -130]
 [  -4  -28   -3]]




A5 = 
[[ 0 -3  8]
 [ 9  6 -1]
 [-7  2  4]]

B5 = 
[[-5  8 -7]
 [ 1  0 -2]
 [ 6 -4  3]]

A5 * B5 = 
[[ 45 -32  30]
 [-45  76 -78]
 [ 61 -72  57]]
